### ISSUE TITLE
Feature Request - Birthdays

### ISSUE THREAD

**Issue by AlphaOmega2020** [Injabie3/lui-cogs-v3#1]
Hi,

Can this be made so each member can assign their own birthday? Currently i seem only able to do so if i have admin/mod rights.

**Comment by Injabie3** [comment]
Resolved after 97ea4f172edd0f524f85c46ed0ddb6b1b6bea4ab . Enable via `[p]birthday selfbirthday` and then use `[p]birthday self set`.
