### ISSUE TITLE
qrchecker alias overlap

### ISSUE THREAD

**Issue by Technetium1** [Injabie3/lui-cogs-v3#6]
https://github.com/Injabie3/lui-cogs-v3/blob/cb307366d15754445a73cf38745d75f97bac9ab8/qrchecker/qrchecker.py#L139 this alias of `qr` breaks the ability to use [Kreusada's QR](https://github.com/Kreusada/Kreusada-Cogs/tree/master/qr). Trying to load fails with:
> This package could not be loaded for the following reason:
`qr`: Command `qr` is already an existing command or alias in one of the loaded cogs.

**Comment by Injabie3** [comment]
Good to know. I don't use the other QR cog, but given that it was a shorthand for settings, will remove this alias in the next commit and just use the Alias cog for it.

**Comment by Technetium1** [comment]
Thanks! Don't forget to bump the version :)
